OregonStateUniversity/MyEventBoard

.github/workflows/build_test.yml, .gitignore, bin/pre-push, composer.json, docs/TESTS.md, run_tests_php.sh, set_permissions.sh, tests/BrowseTest.php, tests/CreateTest.php, tests/EditTest.php, tests/ErrorTest.php, tests/EventsTest.php, tests/IndexTest.php, tests/LoginTest.php, tests/ManageTest.php, tests/RegisterTest.php, tests/ReservationDetailsTest.php, tests/ReservationsTest.php, tests/src/DeleteEventTest.php, tests/src/DeleteReservationTest.php, tests/src/EditEventDetailsTest.php, tests/src/EditEventSlotsTest.php, tests/src/FillDashboardTest.php, tests/src/InsertEventTest.php, tests/src/ReserveSlotTest.php, tests/src/UploadTest.php
- Add PHPUnit and file permissions test for all PHP files
- Run tests on pre-push hook
- Add github action to run tests in PRs
Code quality.
Tests ran when pushing this branch and after opening this PR.
=> chore(phpunit): add initial tests

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, README.md, docs/GETTING_STARTED.md, docs/INSTALLATION.md
- Add PR and issue templates
- Add code of conduct
- Update readme and installation docs
Setting community standards.
N/A
=> docs: add templates and code of conduct

.github/workflows/commitlint.yml, commitlint.config.js, composer.json, composer.lock, set_permissions.sh
- Downgrade PHPUnit version to be compatible with PHP 7.2
- Fix commitlint action
- Remove merge conflict artifacts in set_permissions
Compatibility with server application versions.
Locally and on personal staging env.
=> fix(phpunit): change version to compatible with php7.2

composer.json, composer.lock
Specify specific versions of packages to use.
Server runs PHP 7.2.28, so we need to use compatible packages.
On my staging.
=> build(composer): use specific package versions

composer.json
Remove github hooks.
Problem with Windows compatibility.
=> build(hooks): remove github hooks

dashboard.php, logout.php, templates/layout/logged_in_layout.twig, templates/layout/logged_out_layout.twig, templates/partials/side.twig, templates/views/home.twig, templates/views/manage.twig
Added logout button to Nav bar and routed to landing page after logout
Needed a logout page
I tested this locally
=> feat(logout): add logout route

index.php, login.php, templates/views/browse.twig, templates/views/create.twig, templates/views/edit.twig, templates/views/error.twig, templates/views/events.twig, templates/views/home.twig, templates/views/login.twig, templates/views/main.twig, templates/views/manage.twig, templates/views/register.twig, templates/views/reservation_details.twig, templates/views/reservations.twig
Update layout names in templates.
Follow up to #14.
Locally and staging.
=> feat(layouts): update layout names

src/upload.php, templates/views/register.twig, templates/views/reservation_details.twig
chagned text in templates/views/reservation_details.twig and templates/views/register.twig 
to let users know that they can only upload a single file.
There was no way for users to know they could only upload a single file.
manual tests, visual inspection of new text
- [ x] All new and existing tests passed.
=> fix: fix file upload text

src/upload.php
current accepted file types are txt, pdf, zip, docx, xlsx, and pptx.  More can be added by putting them in the array
This is a new feature
Manual tests with differnt file types.  I don'thave have ms office to test ms office file types
- [x ] All new and existing tests passed.
=> feat: added file upload white list

templates/views/browse.twig, templates/views/create.twig, templates/views/edit.twig, templates/views/events.twig, templates/views/home.twig, templates/views/login.twig, templates/views/main.twig, templates/views/register.twig, templates/views/reservation_details.twig, templates/views/reservations.twig
Clean up twig files in templates/views
I've tested this locally
=> refactor: remove redudant javascript from views

config/database.php, manage.php, src/creator_upload.php, src/upload.php, templates/layout/logged_in_layout.twig, templates/partials/header.twig, templates/partials/side.twig, templates/views/home.twig, templates/views/manage.twig, templates/views/reservation_details.twig
Add missing upload.js
Fixing after demo.
On server.
=> fix(uploads): add missing js

static/css/createStyle.css, static/css/editStyle.css, static/css/eventStyle.css, static/css/manageStyle.css, static/css/registerStyle.css, static/css/reservationDetailsStyle.css, static/css/reservationsStyle.css, templates/layout/logged_in_layout.twig, templates/views/create.twig, templates/views/manage.twig, templates/views/reservation_details.twig, templates/views/reservations.twig
- Fix datepicker references.
- Add missing CSS files.
Errors in UI.
Staging.
=> fix(datepicker): fix references

config/database.php, manage.php, reservation_details.php, src/delete_event.php, src/delete_file.php, static/view_js/manage.js, static/view_js/reservation_details.js, templates/views/manage.twig, templates/views/reservation_details.twig
delete event should recursivly delete the event file folder.
uploading a file should delete a previously uploaded file.
deleting a reservation should delete an uploaded file
removing an attendee should delete an uploaded file
without this files will be stuck in the uploads folder forever!
manual tests, regression tests
=> feat: deleting events/reservations will delete uploaded files as well

.gitignore, scheduleit/.gitignore, scheduleit/static/css/calendar.css, scheduleit/views/meetings/create.twig
changes color of active & inactive cells in monthly calendar view during meeting creation
User can see if a cell is active or inactive by its color
It's necessary for user to un-select a specified time
This has been tested locally and on staging area
=> feat: change color of active cell

config/database.php, manage.php, src/onid_invite.php, static/view_js/manage.js, templates/views/manage.twig
this enable mass event inivte by putting a list of space seperated onids in the field.  It wil also list all onids that were invited but have not registered
this is a client requested feature
manual regression tests
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have done [regression tests](docs/REGRESSION_TESTS.md) after my changes.
- [ x] All new and existing tests passed.
=> feat: email invites from manage page

config/session.php, scheduleit/config/database.php, scheduleit/config/routes.php, scheduleit/views/home/login.php
Redirects from login page to meetings page in production. If you're not logged in, you'll be directed to OSU login.
Login page is only accessible in development.
Staging.
=> fix(login): redirect to meetings in production

scheduleit/config/database.php, scheduleit/views/meetings/_invite_card.twig, scheduleit/views/meetings/index.php, scheduleit/views/meetings/index.twig, static/view_js/manage.js
implemented the invite list for the meetings page.  It will only appear if you have invites and do not have a booking for the same event.  Also fixed a bug in the old site manage.js
new feature for the new site
just manual tests with database manipulation and using old site to create and invite to meetings
- [ x] New feature (non-breaking change which adds functionality)
=> feat: meetings invite list works correctly

static/view_js/manage.js, templates/views/manage.twig
return to original code that works correctly
the change suggestions did not generate a correct link and would occaionally grab the entire lsit of names as a single onid
to invite
manual tests
=> fix: return to original version of email invite

.gitignore, .htaccess.example, composer.json, composer.lock, db/migrations/01_create_user_table.php, db/migrations/02_create_event_table.php, db/migrations/03_create_timeslot_table.php, db/migrations/04_create_booking_table.php, db/migrations/05_create_timeslot_procedures.php, db/migrations/06_create_files_table.php, db/migrations/07_create_invites_table.php, docs/DATABASE.md, phinx.php, scheduleit.config.php, scheduleit/.htaccess.example, set_permissions.sh, setup.sh
- Add database migrations to enable the database to be recreated.
- Check for `.htaccess` and `.env` files and exit the application if they are missing.
- Update `setup.sh` to run migrations and download Composer only if it's missing.
There's no current record of the database structure. Using migrations also allows us to track changes.
On a clean database.
=> build(migrations): add db migrations and instructions

scheduleit/views/meetings/_meeting_details_mine.twig, scheduleit/views/meetings/show.php
readded the feature to invite by a list of space ceperated onid ids
because the new site doesn't have this feature
manual tests
- [? ] Bug fix (non-breaking change which fixes an issue)
- [? ] New feature (non-breaking change which adds functionality)
- [x ] All new and existing tests passed.
=> feat: invite by onid from _meeting_details_mine.twig

scheduleit/static/js/create.js, scheduleit/views/layouts/logged_in.twig, scheduleit/views/meetings/_meeting_form.twig
updated the new create page location section to include the osu location list
it returns functionality from the original site
just manual tests
- [ x] My code follows the code style of this project.
=> fix: added location list to create meeting page

composer.json, composer.lock, config/database.php, config/session.php, db/migrations/03_create_timeslot_table.php, scheduleit.config.php, scheduleit/config/database.php, scheduleit/static/css/alerts.css, scheduleit/views/layouts/logged_in.twig, scheduleit/views/meetings/_meeting_form.twig, scheduleit/views/meetings/create.php, scheduleit/views/meetings/create.twig, src/onid_invite.php
=> feat(create event): start hooking up create

config/session.php, db/migrations/03_create_timeslot_table.php, db/migrations/04_create_booking_table.php, db/migrations/06_create_files_table.php, db/migrations/07_create_invites_table.php, scheduleit.config.php, scheduleit/config/database.php, scheduleit/config/twig.php, scheduleit/lib/send_email.php, scheduleit/lib/upload.php, scheduleit/views/calendar/index.twig, scheduleit/views/invites/show.php, scheduleit/views/invites/show.twig, scheduleit/views/layouts/logged_in.twig, scheduleit/views/meetings/index.php, scheduleit/views/meetings/index.twig, setup.sh
- Get invite to a working state.
- Create upload class.
- Create send email class.
- Add missing cascade delete in db migrations.
Creating classes for upload and send email will make it easier to write unit tests in the future.
On staging: https://web.engr.oregonstate.edu/~sibolibb/MyEventBoard/scheduleit/
=> feat(invite): save timeslot and upload

scheduleit/config/database.php, scheduleit/config/routes.php, scheduleit/static/js/show.js, scheduleit/views/meetings/remove_attendee.php, scheduleit/views/meetings/show.php, scheduleit/views/meetings/show.twig
this implements onid invite, remove attendee, update slots after removing an attendee, and notify an attendee they were removed from an event
returning features!
manual tests
=> feat: onid invite, remove attendee, update slots, email notify

config/database.php, scheduleit/config/database.php, scheduleit/static/js/manage.js, scheduleit/views/layouts/logged_in.twig, scheduleit/views/manage/index.twig
fixes old database, removes double deletebooking from new database and fixes getMeetingsAttendees in new database
faith and dreams
=> fix: database and logged_in

scheduleit.config.php, scheduleit/config/database.php, scheduleit/config/twig.php, scheduleit/lib/upload.php, scheduleit/views/manage/index.twig, scheduleit/views/meetings/_meeting_card.twig, scheduleit/views/meetings/index.php, scheduleit/views/meetings/remove_attendee.php, scheduleit/views/meetings/show.php
- On meetings page, show attendees of same meeting on same card
- Update card style
- Sort manage page by meeting last updated
- Whitespace and formatting cleanup
- Add SITE_URL constant
- Fix upload file permission
Requests from client.
Locally.
=> feat(cards): group attendees on single card

scheduleit/lib/send_email.php, scheduleit/static/js/show.js, scheduleit/views/meetings/remove_attendee.php, scheduleit/views/meetings/show.php, scheduleit/views/meetings/show.twig
redid the invite email with the new email class.  Also added the notify email
the people need to know
manaul tests
=> fix: invite and removed from meeting emails

scheduleit/config/database.php, scheduleit/views/meetings/edit.php, scheduleit/views/meetings/edit.twig
added delete functionality to delete button on edit page
so we can delete event
manual tests
- [ x] New feature (non-breaking change which adds functionality)
=> feat: delete event from edit page

scheduleit/static/js/show.js, scheduleit/views/meetings/show.twig
improved the way the remove attendee button works
this is better
manual tests
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix: fixed show.js and show.twig

scheduleit/lib/file_upload.php, scheduleit/views/home/login.php, scheduleit/views/invites/show.php
added isset conditional before using $booking['timeslot_id']
fixed server error message
manual tests
=> fix: bug in invite/show.php

scheduleit/lib/file_upload.php, scheduleit/views/meetings/edit.php
added delete event upload folder/files when deleting an event
original site feature
manual tests
=> Develop mc delete event files

scheduleit/lib/file_upload.php
Update file upload method to remove old files that match file name before upload.
Keeping folders clean.
Locally.
=> feat(delete files): remove previous uploaded files

db/migrations/08_add_mod_date_to_invites.php, scheduleit/views/meetings/show.twig
- Add mod_date to invites
- Move invite form to modal
Cleaner look.
Locally.
=> feat(invited): add mod_date to invites

scheduleit/config/database.php, scheduleit/lib/file_upload.php, scheduleit/static/js/meeting_show.js, scheduleit/views/meetings/remove_attendee.php, scheduleit/views/meetings/show.twig
removing a meeting attendee will also delete any file they had uploaded
we need to save space
manual tests
- [ x] My code follows the code style of this project.
=> feat: remove attendee deletes their file

scheduleit/views/meetings/_meeting_card.twig, scheduleit/views/meetings/_meeting_info_form_fields.twig, scheduleit/views/meetings/show.twig
when clicking an uploaded file the user will get a download prompt instead of visiting the file on the server
seems better
manual test
- [? ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
=> fix: clicking files will prompt a download

scheduleit/config/database.php, scheduleit/lib/file_upload.php, scheduleit/lib/send_email.php, scheduleit/static/css/_global.css, scheduleit/static/css/times_selector.css, scheduleit/static/js/calendar.js, scheduleit/static/js/meeting_form.js, scheduleit/views/home/login.php, scheduleit/views/home/login.twig, scheduleit/views/layouts/logged_in.twig, scheduleit/views/layouts/logged_out.twig, scheduleit/views/meetings/_meeting_card.twig, scheduleit/views/meetings/_meeting_dates_form_fields.twig, scheduleit/views/meetings/create.php, scheduleit/views/meetings/edit_dates.php, scheduleit/views/meetings/edit_dates.twig, scheduleit/views/meetings/index.php, scheduleit/views/meetings/index.twig, scheduleit/views/meetings/show.php, scheduleit/views/meetings/show.twig
- Enable adding and removing time slots to existing meeting
- Email users if timeslot is removed
- Show all meeting attendees to each attendee if meeting is not anonymous
Needed functionality.
Locally.
=> feat(timeslots): add and delete timeslots on meeting edit

scheduleit/lib/file_upload.php, scheduleit/static/js/meeting_form.js, scheduleit/views/meetings/show.php
Disabled the file upload white list as requested by the client
Invitation links sent are correct now
when changing the time slot duration during a meeting edit the modal will hide when clicking update
small bug fixes
manual tests
=> fix: disable white list, invite link correction, duration modal hide

scheduleit/static/css/times_selector.css, scheduleit/static/js/meeting_form.js, scheduleit/views/meetings/_meeting_dates_form_fields.twig, scheduleit/views/meetings/edit_dates.php
- Add "paint" ability to times selector
- Add helper text so user knows the feature is there
- Reset duration on cancel
- Remove all timeslots from DB if duration is changed
- Fix `send_email` typo
Bugs
Locally
=> fix(timeslots): add paint ability to selector

scheduleit/views/meetings/_meeting_info_form_fields.twig
just added download tag to the file link in the edit page
small bug fix
manual tests
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix: meeting edit page file link download

scheduleit/config/database.php, scheduleit/views/meetings/edit_dates.php
when removing a timeslot will remove a meeting attendee that uploaded a file the file will be deleted 
clear out ghost files
quick manual tests
=> fix: delete uploaded files if timeslot removes attendee

scheduleit/static/js/meeting_form.js, scheduleit/views/meetings/edit_dates.twig
Collect removed times and ask user to confirm once when saving meeting.
Fewer modals for user to go through.
Locally
=> feat(timeslots): ask on save to remove timeslots

lib/file_upload.php, views/invites/show.twig
recursively set file permissions after file upload
allows file downloads to work
manual tests
=> fix: set correct file permissions

views/invites/show.twig, views/meetings/_meeting_info_form_fields.twig
commented out the white list text from the upload text box
so as to not confuse future users
manual tests
=> fix: update the upload file text box because white list is off

docs/REGRESSION_TESTS.md
small update to regression tests
just improve them
- [x ] I have updated the documentation accordingly.
=> fix: small adjustment to regression tests

CONTRIBUTING.md, README.md, docs/CODE_STYLE.md, docs/FILE_UPLOADS.md, docs/STATIC.md, lib/file_upload.php, set_permissions.sh, views/invites/show.twig, views/meetings/_meeting_info_form_fields.twig
Add file uploads doc
Add TODOS
Fix typos
Documenting the process.
N/A
=> docs(app): add file uploads doc and TODOS
